// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppBiblioteca.Models;

namespace WebAppBiblioteca.Migrations
{
    [DbContext(typeof(WebAppBibliotecaContext))]
    partial class WebAppBibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppBiblioteca.Models.General", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.Property<int?>("TipoGeneralId");

                    b.HasKey("Id");

                    b.HasIndex("TipoGeneralId");

                    b.ToTable("General");
                });

            modelBuilder.Entity("WebAppBiblioteca.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AreaId");

                    b.Property<int>("DiasPrestamo");

                    b.Property<string>("Editorial");

                    b.Property<int?>("TipoLibroId");

                    b.Property<string>("Titulo");

                    b.Property<int?>("UbicacionId");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("TipoLibroId");

                    b.HasIndex("UbicacionId");

                    b.ToTable("Libro");
                });

            modelBuilder.Entity("WebAppBiblioteca.Models.TipoGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("TipoGeneral");
                });

            modelBuilder.Entity("WebAppBiblioteca.Models.General", b =>
                {
                    b.HasOne("WebAppBiblioteca.Models.TipoGeneral", "TipoGeneral")
                        .WithMany("datosGenerales")
                        .HasForeignKey("TipoGeneralId");
                });

            modelBuilder.Entity("WebAppBiblioteca.Models.Libro", b =>
                {
                    b.HasOne("WebAppBiblioteca.Models.General", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("WebAppBiblioteca.Models.General", "TipoLibro")
                        .WithMany()
                        .HasForeignKey("TipoLibroId");

                    b.HasOne("WebAppBiblioteca.Models.General", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("UbicacionId");
                });
#pragma warning restore 612, 618
        }
    }
}
